name: LAMP Deployment

on:
    workflow_dispatch: #mauell Job starten
    #push:
    #  branches:
     # - main
    #pull_request:
 
jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Linting
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
          kurs/ansible/inventory.yml
          kurs/ansible/playbook.yml

        args: "-c kurs/ansible/.ansible-lint"