#----------------------------------
# Dima Testen v001
#
#----------------------------------

name: GitHub-Master-basics
#env:
#  Application_Name  :   "Bier_App"
#  Package_Name      :   "Bier_App_Version-${{ github.sha }}"
  

on:
 push:
   branches: 
     - main
   
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: nur ein Test
        run:  echo "Hello Wordld from Testing Job"
        
      - name: nur ein Test
        run:  |
              echo "Meesages1"
              echo "Applikation name: ${{ env.Application_Name }}"
              
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: nur ein Test
        run:  echo "Hello Wordld from deploy Job"
  
      - name: Print Deploment Package
        run:  echo "Deploment Package name und Version ${{ env.Package_Name  }}"

      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi



      - name: write inventory to file
        env:
          INVENTORY: ${{ secrets.INVENTORY }}
        run: 'echo "$INVENTORY" > inventory'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: run playbook
        run: |
               ansible-playbook -i inventory ansible/hello-world.yaml
  
