#----------------------------------
# Dima Testen v001
#
#----------------------------------

name: GitHub-Master-basics

on:
 push:
   branches: 
     - main
   
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: nur ein Test
        run:  echo "Hello Wordld from Testing Job"
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: nur ein Test
        run:  echo "Hello Wordld from deploy Job"
  



  



